[workspace]
members = [ "zym", "zym-config", "zym-logger", "zym-model", "zym-listener", "zym-controller", "zym-manager", "zym-usecase", "zym-draw" ]

[workspace.package]
version = "0.1.0"
authors = ["Teruki Tada"]
edition = "2021"