[workspace]
members = [ "zym", "zym-config", "zym-logger", "zym-model", "zym-session", "zym-controller", "zym-manager", "zym-usecase" ]

[workspace.package]
version = "0.1.0"
authors = ["Teruki Tada"]
edition = "2021"