[workspace]
members = [
    "wm_main",
    "wm_config",
    "wm_logger",
    "wm_model",
    "wm_listener",
    "wm_controller",
    "wm_manager",
    "wm_usecase",
    "wm_draw"
]

[workspace.package]
version = "0.1.0"
authors = ["Teruki Tada"]
edition = "2021"
