[package]
name = "wm_drawing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.16", features = ["xcb"] }
wm_config = { path = "../wm_config" }
log = "0.4"